=== francesconero/HorseFever/src/main/resources/GUI/RisorseGUI.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT ROOT (Risorsa*)>
<!ELEMENT Risorsa EMPTY>
<!ATTLIST Risorsa
	nome CDATA #REQUIRED
	percorso CDATA #REQUIRED>

=== francesconero/HorseFever/resources/GUI/RisorseGUI.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ROOT SYSTEM "RisorseGUI.dtd" >
<ROOT>
	<Risorsa
		percorso="resources/immagini/FamilyGame/Tabellone.jpg"
		nome="Tabellone" />
	<Risorsa
		percorso="resources/immagini/FamilyGame/SegnaliniQuotazioniScuderie/SegnalinoQuotazioniScuderiaBianca.jpg"
		nome="SegnalinoQuotazioneBianco" />
	<Risorsa
		percorso="resources/immagini/FamilyGame/SegnaliniQuotazioniScuderie/SegnalinoQuotazioniScuderiaBlu.jpg"
		nome="SegnalinoQuotazioneBlu" />
	<Risorsa
		percorso="resources/immagini/FamilyGame/SegnaliniQuotazioniScuderie/SegnalinoQuotazioniScuderiaGialla.jpg"
		nome="SegnalinoQuotazioneGiallo" />
	<Risorsa
		percorso="resources/immagini/FamilyGame/SegnaliniQuotazioniScuderie/SegnalinoQuotazioniScuderiaNera.jpg"
		nome="SegnalinoQuotazioneNero" />
	<Risorsa
		percorso="resources/immagini/FamilyGame/SegnaliniQuotazioniScuderie/SegnalinoQuotazioniScuderiaRossa.jpg"
		nome="SegnalinoQuotazioneRosso" />
	<Risorsa
		percorso="resources/immagini/FamilyGame/SegnaliniQuotazioniScuderie/SegnalinoQuotazioniScuderiaVerde.jpg"
		nome="SegnalinoQuotazioneVerde" />
	<Risorsa
		percorso="resources/immagini/FamilyGame/AzioniNegative/retro.jpg"
		nome="RetroCarteAzione" />
	<Risorsa
		percorso="resources/immagini/FamilyGame/SegnaliniScommessa/PiazzataBianco.jpg"
		nome="PiazzataBianco" />
	<Risorsa
		percorso="resources/immagini/FamilyGame/SegnaliniScommessa/PiazzataBlu.jpg"
		nome="PiazzataBlu" />
	<Risorsa
		percorso="resources/immagini/FamilyGame/SegnaliniScommessa/PiazzataGiallo.jpg"
		nome="PiazzataGiallo" />
	<Risorsa
		percorso="resources/immagini/FamilyGame/SegnaliniScommessa/PiazzataNero.jpg"
		nome="PiazzataNero" />
	<Risorsa
		percorso="resources/immagini/FamilyGame/SegnaliniScommessa/PiazzataRosso.jpg"
		nome="PiazzataRosso" />
	<Risorsa
		percorso="resources/immagini/FamilyGame/SegnaliniScommessa/PiazzataVerde.jpg"
		nome="PiazzataVerde" />
	<Risorsa
		percorso="resources/immagini/FamilyGame/SegnaliniScommessa/VincenteBianco.jpg"
		nome="VincenteBianco" />
	<Risorsa
		percorso="resources/immagini/FamilyGame/SegnaliniScommessa/VincenteBlu.jpg"
		nome="VincenteBlu"></Risorsa>
	<Risorsa
		percorso="resources/immagini/FamilyGame/SegnaliniScommessa/VincenteGiallo.jpg"
		nome="VincenteGiallo" />
	<Risorsa
		percorso="resources/immagini/FamilyGame/SegnaliniScommessa/VincenteNero.jpg"
		nome="VincenteNero" />
	<Risorsa
		percorso="resources/immagini/FamilyGame/SegnaliniScommessa/VincenteRosso.jpg"
		nome="VincenteRosso" />
	<Risorsa
		percorso="resources/immagini/FamilyGame/SegnaliniScommessa/VincenteVerde.jpg"
		nome="VincenteVerde" />
	<Risorsa
		percorso="resources/immagini/FamilyGame/IconeScuderie/horseFever-55.jpg"
		nome="BIANCO" />
	<Risorsa
		percorso="resources/immagini/FamilyGame/IconeScuderie/horseFever-56.jpg"
		nome="BLU"></Risorsa>
	<Risorsa
		percorso="resources/immagini/FamilyGame/IconeScuderie/horseFever-57.jpg"
		nome="GIALLO" />
	<Risorsa
		percorso="resources/immagini/FamilyGame/IconeScuderie/horseFever-58.jpg"
		nome="NERO" />
	<Risorsa
		percorso="resources/immagini/FamilyGame/IconeScuderie/horseFever-59.jpg"
		nome="ROSSO" />
	<Risorsa
		percorso="resources/immagini/FamilyGame/IconeScuderie/horseFever-60.jpg"
		nome="VERDE" />
	<Risorsa
		percorso="resources/immagini/box_front_HF_640.jpg"
		nome="Cover" />
</ROOT>

=== francesconero/HorseFever/src/main/resources/GUI/RisorseGUI.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ROOT SYSTEM "RisorseGUI.dtd" >
<ROOT>
	<Risorsa
		percorso="src/main/resources/immagini/FamilyGame/Tabellone.jpg"
		nome="Tabellone" /><Risorsa
		percorso="src/main/resources/immagini/FamilyGame/SegnaliniQuotazioniScuderie/SegnalinoQuotazioniScuderiaBianca.jpg"
		nome="SegnalinoQuotazioneBianco" /><Risorsa
		percorso="src/main/resources/immagini/FamilyGame/SegnaliniQuotazioniScuderie/SegnalinoQuotazioniScuderiaBlu.jpg"
		nome="SegnalinoQuotazioneBlu" /><Risorsa
		percorso="src/main/resources/immagini/FamilyGame/SegnaliniQuotazioniScuderie/SegnalinoQuotazioniScuderiaGialla.jpg"
		nome="SegnalinoQuotazioneGiallo" /><Risorsa
		percorso="src/main/resources/immagini/FamilyGame/SegnaliniQuotazioniScuderie/SegnalinoQuotazioniScuderiaNera.jpg"
		nome="SegnalinoQuotazioneNero" /><Risorsa
		percorso="src/main/resources/immagini/FamilyGame/SegnaliniQuotazioniScuderie/SegnalinoQuotazioniScuderiaRossa.jpg"
		nome="SegnalinoQuotazioneRosso" /><Risorsa
		percorso="src/main/resources/immagini/FamilyGame/SegnaliniQuotazioniScuderie/SegnalinoQuotazioniScuderiaVerde.jpg"
		nome="SegnalinoQuotazioneVerde" /></ROOT>
